name : "My first CI workflow using GitHub Actions"

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn clean install

   # - name: perform code analysis with SonarQube
    #  uses: sonarsource/sonarcloud-github-action@master
     # with:
      # args: >
       #  -Dsonar.projectKey=your_project_key
        # -Dsonar.organization=your_organization
         #-Dsonar.host.url=https://sonarcloud.io
         #-Dsonar.login=${{ secrets.SONAR_TOKEN }} 



